name: Build and Deploy TOIREx Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Clear pip cache
        run: pip cache purge

      - name: Remove old builds
        run: rm -rf docs/_build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-rtd-theme sphinxcontrib-mermaid
          pip install -e .

      - name: Build docs
        run: make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          force_orphan: true
